
function drdthetaSSN = drdthetaSSN(r, theta, phi)

    BField = BfieldKSM(r, theta, phi);
    Bx = BField(1);
    By = BField(2);
    Bz = BField(3);
    
%         drdthetaSSN = ( r*cot(theta)*(2*M - r^3) ) / ( 4*M+r^3 );


drdthetaSSN = (4.*By.^2+4.*Bx.^2.*cos(theta).^2+8.*Bx.*Bz.*cos(theta).*sin( ...
  theta)+(-1).*sin(theta).^2+4.*Bz.^2.*sin(theta).^2).^(-1).*((-2).* ...
  (Bx.^2.*r.^2+By.^2.*r.^2+(-4).*Bx.^2.*By.^2.*r.^2+(-4).*By.^4.* ...
  r.^2+(-4).*By.^2.*Bz.^2.*r.^2).^(1/2)+(-4).*Bx.*Bz.*r.*cos(theta) ...
  .^2+r.*cos(theta).*sin(theta)+4.*Bx.^2.*r.*cos(theta).*sin(theta)+ ...
  (-4).*Bz.^2.*r.*cos(theta).*sin(theta)+4.*Bx.*Bz.*r.*sin(theta) ...
  .^2);


% drdthetaSSN = (4.*By.^2+4.*Bx.^2.*cos(theta).^2+8.*Bx.*Bz.*cos(theta).*sin( ...
%   theta)+(-1).*sin(theta).^2+4.*Bz.^2.*sin(theta).^2).^(-1).*(2.*( ...
%   Bx.^2.*r.^2+By.^2.*r.^2+(-4).*Bx.^2.*By.^2.*r.^2+(-4).*By.^4.* ...
%   r.^2+(-4).*By.^2.*Bz.^2.*r.^2).^(1/2)+(-4).*Bx.*Bz.*r.*cos(theta) ...
%   .^2+r.*cos(theta).*sin(theta)+4.*Bx.^2.*r.*cos(theta).*sin(theta)+ ...
%   (-4).*Bz.^2.*r.*cos(theta).*sin(theta)+4.*Bx.*Bz.*r.*sin(theta) ...
%   .^2);

end