function drMeridianCAN_1 = drMeridianCAN_1(CoordinateDetails, theta, r, SystemParameters)

    if strcmp(CoordinateDetails.Units, 'Rp')
        ConvFactor = SystemParameters.Rp ./ SystemParameters.r0;
    elseif strcmp(CoordinateDetails.Units, 'r0')
        ConvFactor = 1;
    end

    R = r .* ConvFactor;
    CoordinateDetails.Units = 'r0';

%     CAN_DiskParameters = SystemParameters.CAN_DiskParameters;
%     beta = SystemParameters.Beta;
%     M = SystemParameters.M;
% 
%     ThetaTilt = SystemParameters.Tilt.Theta;
%     PhiTilt = SystemParameters.Tilt.Phi;
        
    
    PhiMeridian = acos(sin(SystemParameters.Tilt.Phi)*sin(SystemParameters.Tilt.Theta)) ;
%     PhiMeridian = pi/2;
%     B_Disk = B_CAN_Spherical(CAN_DiskParameters, r, theta, PhiMeridian);


    PointCoordinates = horzcat([PhiMeridian; theta; R], [0; 0; 0]);
    B_Cartesian_KSM = BField(CoordinateDetails, PointCoordinates, SystemParameters);    
    Bx = B_Cartesian_KSM(1);
    By = B_Cartesian_KSM(2);
    Bz = B_Cartesian_KSM(3);
    
%     B_Disk = [0, 0];
% 
%     B_CAN_r = B_Disk(1);
%     B_CAN_theta = B_Disk(2);

drMeridianCAN_1 = ((-4).*Bx.*By.*r.*cos (PhiMeridian).*cos (theta).^2+(-4).*Bx.*Bz.*r.*cos ( ...
  theta).^2.*sin(PhiMeridian)+(-1).*2.^(1/2).*(2.*Bx.^2.*r.^2+By.^2.*r.^2+( ...
  -4).*Bx.^2.*By.^2.*r.^2+(-4).*By.^4.*r.^2+Bz.^2.*r.^2+(-4).* ...
  Bx.^2.*Bz.^2.*r.^2+(-8).*By.^2.*Bz.^2.*r.^2+(-4).*Bz.^4.*r.^2+(-1) ...
  .*By.^2.*r.^2.*cos(2.*PhiMeridian)+4.*Bx.^2.*By.^2.*r.^2.*cos(2.*PhiMeridian)+4.* ...
  By.^4.*r.^2.*cos(2.*PhiMeridian)+Bz.^2.*r.^2.*cos(2.*PhiMeridian)+(-4).*Bx.^2.* ...
  Bz.^2.*r.^2.*cos(2.*PhiMeridian)+(-4).*Bz.^4.*r.^2.*cos(2.*PhiMeridian)+(-2).*By.* ...
  Bz.*r.^2.*sin(2.*PhiMeridian)+8.*Bx.^2.*By.*Bz.*r.^2.*sin(2.*PhiMeridian)+8.* ...
  By.^3.*Bz.*r.^2.*sin(2.*PhiMeridian)+8.*By.*Bz.^3.*r.^2.*sin(2.*PhiMeridian)).^( ...
  1/2)+r.*cos (theta).*sin(theta)+4.*Bx.^2.*r.*cos (theta).*sin(theta) ...
  +(-4).*By.^2.*r.*cos (PhiMeridian).^2.*cos (theta).*sin(theta)+(-8).*By.* ...
  Bz.*r.*cos (PhiMeridian).*cos (theta).*sin (PhiMeridian).*sin(theta)+(-4).*Bz.^2.*r.* ...
  cos (theta).*sin (PhiMeridian).^2.*sin(theta)+4.*Bx.*By.*r.*cos (PhiMeridian).*sin ( ...
  theta).^2+4.*Bx.*Bz.*r.*sin (PhiMeridian).*sin (theta).^2).*(4.*Bz.^2.*cos ( ...
  PhiMeridian).^2+4.*Bx.^2.*cos (theta).^2+(-8).*By.*Bz.*cos (PhiMeridian).*sin(PhiMeridian)+ ...
  4.*By.^2.*sin (PhiMeridian).^2+8.*Bx.*By.*cos (PhiMeridian).*cos (theta).*sin(theta)+ ...
  8.*Bx.*Bz.*cos (theta).*sin (PhiMeridian).*sin(theta)+(-1).*sin (theta).^2+ ...
  4.*By.^2.*cos (PhiMeridian).^2.*sin (theta).^2+8.*By.*Bz.*cos (PhiMeridian).*sin(PhiMeridian) ...
  .*sin (theta).^2+4.*Bz.^2.*sin (PhiMeridian).^2.*sin (theta).^2).^(-1);


% 
% 
% (1/2).*((-4).*M.^2.*cos (PhiMeridian).^2+r.^6.*cos (PhiMeridian).^2.*cos(PhiTilt) ...
%   .^2.*cos (ThetaTilt).^2+(-2).*r.^6.*cos (PhiMeridian).*cos (PhiTilt).*cos ( ...
%   ThetaTilt).*sin (PhiMeridian).*sin (PhiTilt).*sin(theta)+(-16).*M.^2.*sin ( ...
%   PhiMeridian).^2.*sin (theta).^2+r.^6.*sin (PhiMeridian).^2.*sin (PhiTilt).^2.*sin ( ...
%   theta).^2+2.*r.^6.*cos (PhiMeridian).*cos (PhiTilt).^2.*cos (theta).*cos ( ...
%   ThetaTilt).*sin (PhiMeridian).*sin(ThetaTilt)+(-2).*r.^6.*cos (PhiTilt).* ...
%   cos (theta).*sin (PhiMeridian).^2.*sin (PhiTilt).*sin (theta).*sin(ThetaTilt)+ ...
%   r.^6.*cos (PhiTilt).^2.*cos (theta).^2.*sin (PhiMeridian).^2.*sin(ThetaTilt) ...
%   .^2).^(-1).*((-1).*r.*(2.*r.^6.*cos (PhiMeridian).*cos (PhiTilt).^2.*cos ( ...
%   ThetaTilt).^2.*sin(PhiMeridian)+16.*M.^2.*cos (theta).*sin (PhiMeridian).^2.*sin( ...
%   theta)+2.*r.^6.*cos (PhiMeridian).^2.*cos (PhiTilt).*cos (ThetaTilt).*sin ( ...
%   PhiTilt).*sin(theta)+(-2).*r.^6.*cos (PhiTilt).*cos (ThetaTilt).* ...
%   sin (PhiMeridian).^2.*sin (PhiTilt).*sin(theta)+(-2).*r.^6.*cos (PhiMeridian).*sin ( ...
%   PhiMeridian).*sin (PhiTilt).^2.*sin (theta).^2+(-2).*r.^6.*cos (PhiMeridian).^2.*cos ( ...
%   PhiTilt).^2.*cos (theta).*cos (ThetaTilt).*sin(ThetaTilt)+2.*r.^6.* ...
%   cos (PhiTilt).^2.*cos (theta).*cos (ThetaTilt).*sin (PhiMeridian).^2.*sin( ...
%   ThetaTilt)+4.*r.^6.*cos (PhiMeridian).*cos (PhiTilt).*cos (theta).*sin (PhiMeridian).* ...
%   sin (PhiTilt).*sin (theta).*sin(ThetaTilt)+(-2).*r.^6.*cos (PhiMeridian).* ...
%   cos (PhiTilt).^2.*cos (theta).^2.*sin (PhiMeridian).*sin (ThetaTilt).^2)+(-1) ...
%   .*(r.^2.*(2.*r.^6.*cos (PhiMeridian).*cos (PhiTilt).^2.*cos (ThetaTilt).^2.* ...
%   sin(PhiMeridian)+16.*M.^2.*cos (theta).*sin (PhiMeridian).^2.*sin(theta)+2.*r.^6.* ...
%   cos (PhiMeridian).^2.*cos (PhiTilt).*cos (ThetaTilt).*sin (PhiTilt).*sin( ...
%   theta)+(-2).*r.^6.*cos (PhiTilt).*cos (ThetaTilt).*sin (PhiMeridian).^2.*sin ( ...
%   PhiTilt).*sin(theta)+(-2).*r.^6.*cos (PhiMeridian).*sin (PhiMeridian).*sin(PhiTilt) ...
%   .^2.*sin (theta).^2+(-2).*r.^6.*cos (PhiMeridian).^2.*cos (PhiTilt).^2.*cos ( ...
%   theta).*cos (ThetaTilt).*sin(ThetaTilt)+2.*r.^6.*cos (PhiTilt).^2.* ...
%   cos (theta).*cos (ThetaTilt).*sin (PhiMeridian).^2.*sin(ThetaTilt)+4.*r.^6.* ...
%   cos (PhiMeridian).*cos (PhiTilt).*cos (theta).*sin (PhiMeridian).*sin (PhiTilt).*sin ( ...
%   theta).*sin(ThetaTilt)+(-2).*r.^6.*cos (PhiMeridian).*cos (PhiTilt).^2.*cos ( ...
%   theta).^2.*sin (PhiMeridian).*sin (ThetaTilt).^2).^2+4.*r.^2.*(4.*M.^2.*cos ( ...
%   PhiMeridian).^2+4.*M.^2.*cos (theta).^2.*sin (PhiMeridian).^2+(-1).*r.^6.*cos ( ...
%   PhiTilt).^2.*cos (ThetaTilt).^2.*sin (PhiMeridian).^2+(-2).*r.^6.*cos (PhiMeridian).* ...
%   cos (PhiTilt).*cos (ThetaTilt).*sin (PhiMeridian).*sin (PhiTilt).*sin(theta)+( ...
%   -1).*r.^6.*cos (PhiMeridian).^2.*sin (PhiTilt).^2.*sin (theta).^2+2.*r.^6.* ...
%   cos (PhiMeridian).*cos (PhiTilt).^2.*cos (theta).*cos (ThetaTilt).*sin (PhiMeridian).* ...
%   sin(ThetaTilt)+2.*r.^6.*cos (PhiMeridian).^2.*cos (PhiTilt).*cos (theta).* ...
%   sin (PhiTilt).*sin (theta).*sin(ThetaTilt)+(-1).*r.^6.*cos (PhiMeridian).^2.* ...
%   cos (PhiTilt).^2.*cos (theta).^2.*sin (ThetaTilt).^2).*((-4).*M.^2.* ...
%   cos (PhiMeridian).^2+r.^6.*cos (PhiMeridian).^2.*cos (PhiTilt).^2.*cos (ThetaTilt).^2+ ...
%   (-2).*r.^6.*cos (PhiMeridian).*cos (PhiTilt).*cos (ThetaTilt).*sin (PhiMeridian).*sin ( ...
%   PhiTilt).*sin(theta)+(-16).*M.^2.*sin (PhiMeridian).^2.*sin (theta).^2+ ...
%   r.^6.*sin (PhiMeridian).^2.*sin (PhiTilt).^2.*sin (theta).^2+2.*r.^6.*cos ( ...
%   PhiMeridian).*cos (PhiTilt).^2.*cos (theta).*cos (ThetaTilt).*sin (PhiMeridian).*sin( ...
%   ThetaTilt)+(-2).*r.^6.*cos (PhiTilt).*cos (theta).*sin (PhiMeridian).^2.*sin ( ...
%   PhiTilt).*sin (theta).*sin(ThetaTilt)+r.^6.*cos (PhiTilt).^2.*cos ( ...
%   theta).^2.*sin (PhiMeridian).^2.*sin (ThetaTilt).^2)).^(1/2));




% (1/2).*((-4).*M.^2.*cos (PhiMeridian).^2+r.^6.*cos (PhiMeridian).^2.*cos(theta) ...
%   .^2.*sin (SystemParameters.Tilt.Phi).^2+2.*r.^6.*cos (PhiMeridian).*cos (SystemParameters.Tilt.Phi).*cos (theta).* ...
%   cos (SystemParameters.Tilt.Theta).*sin (SystemParameters.Tilt.Phi).*sin(theta)+r.^6.*cos (SystemParameters.Tilt.Phi).^2.* ...
%   cos (SystemParameters.Tilt.Theta).^2.*sin (theta).^2+(-16).*M.^2.*sin (PhiMeridian).^2.*sin ( ...
%   theta).^2+(-2).*r.^6.*cos (PhiMeridian).*cos (SystemParameters.Tilt.Phi).*cos (theta).^2.*sin ( ...
%   PhiMeridian).*sin (SystemParameters.Tilt.Phi).*sin(SystemParameters.Tilt.Theta)+(-2).*r.^6.*cos (SystemParameters.Tilt.Phi).^2.* ...
%   cos (theta).*cos (SystemParameters.Tilt.Theta).*sin (PhiMeridian).*sin (theta).*sin(SystemParameters.Tilt.Theta)+ ...
%   r.^6.*cos (SystemParameters.Tilt.Phi).^2.*cos (theta).^2.*sin (PhiMeridian).^2.*sin(SystemParameters.Tilt.Theta) ...
%   .^2).^(-1).*((-1).*r.*(2.*r.^6.*cos (PhiMeridian).*cos (SystemParameters.Tilt.Phi).*cos(theta) ...
%   .^2.*cos (SystemParameters.Tilt.Theta).*sin(SystemParameters.Tilt.Phi)+2.*r.^6.*cos (SystemParameters.Tilt.Phi).^2.*cos ( ...
%   theta).*cos (SystemParameters.Tilt.Theta).^2.*sin(theta)+16.*M.^2.*cos (theta).*sin ( ...
%   PhiMeridian).^2.*sin(theta)+(-2).*r.^6.*cos (PhiMeridian).^2.*cos (theta).*sin ( ...
%   SystemParameters.Tilt.Phi).^2.*sin(theta)+(-2).*r.^6.*cos (PhiMeridian).*cos (SystemParameters.Tilt.Phi).*cos ( ...
%   SystemParameters.Tilt.Theta).*sin (SystemParameters.Tilt.Phi).*sin (theta).^2+(-2).*r.^6.*cos(SystemParameters.Tilt.Phi) ...
%   .^2.*cos (theta).^2.*cos (SystemParameters.Tilt.Theta).*sin (PhiMeridian).*sin(SystemParameters.Tilt.Theta)+4.* ...
%   r.^6.*cos (PhiMeridian).*cos (SystemParameters.Tilt.Phi).*cos (theta).*sin (PhiMeridian).*sin (SystemParameters.Tilt.Phi).* ...
%   sin (theta).*sin(SystemParameters.Tilt.Theta)+2.*r.^6.*cos (SystemParameters.Tilt.Phi).^2.*cos ( ...
%   SystemParameters.Tilt.Theta).*sin (PhiMeridian).*sin (theta).^2.*sin(SystemParameters.Tilt.Theta)+(-2).*r.^6.* ...
%   cos (SystemParameters.Tilt.Phi).^2.*cos (theta).*sin (PhiMeridian).^2.*sin (theta).*sin ( ...
%   SystemParameters.Tilt.Theta).^2)+(-1).*(r.^2.*(2.*r.^6.*cos (PhiMeridian).*cos (SystemParameters.Tilt.Phi).*cos ( ...
%   theta).^2.*cos (SystemParameters.Tilt.Theta).*sin(SystemParameters.Tilt.Phi)+2.*r.^6.*cos (SystemParameters.Tilt.Phi).^2.* ...
%   cos (theta).*cos (SystemParameters.Tilt.Theta).^2.*sin(theta)+16.*M.^2.*cos (theta).* ...
%   sin (PhiMeridian).^2.*sin(theta)+(-2).*r.^6.*cos (PhiMeridian).^2.*cos (theta).*sin ( ...
%   SystemParameters.Tilt.Phi).^2.*sin(theta)+(-2).*r.^6.*cos (PhiMeridian).*cos (SystemParameters.Tilt.Phi).*cos ( ...
%   SystemParameters.Tilt.Theta).*sin (SystemParameters.Tilt.Phi).*sin (theta).^2+(-2).*r.^6.*cos(SystemParameters.Tilt.Phi) ...
%   .^2.*cos (theta).^2.*cos (SystemParameters.Tilt.Theta).*sin (PhiMeridian).*sin(SystemParameters.Tilt.Theta)+4.* ...
%   r.^6.*cos (PhiMeridian).*cos (SystemParameters.Tilt.Phi).*cos (theta).*sin (PhiMeridian).*sin (SystemParameters.Tilt.Phi).* ...
%   sin (theta).*sin(SystemParameters.Tilt.Theta)+2.*r.^6.*cos (SystemParameters.Tilt.Phi).^2.*cos ( ...
%   SystemParameters.Tilt.Theta).*sin (PhiMeridian).*sin (theta).^2.*sin(SystemParameters.Tilt.Theta)+(-2).*r.^6.* ...
%   cos (SystemParameters.Tilt.Phi).^2.*cos (theta).*sin (PhiMeridian).^2.*sin (theta).*sin ( ...
%   SystemParameters.Tilt.Theta).^2).^2+4.*r.^2.*((-4).*M.^2.*cos (PhiMeridian).^2+r.^6.*cos(PhiMeridian) ...
%   .^2.*cos (theta).^2.*sin (SystemParameters.Tilt.Phi).^2+2.*r.^6.*cos (PhiMeridian).*cos ( ...
%   SystemParameters.Tilt.Phi).*cos (theta).*cos (SystemParameters.Tilt.Theta).*sin (SystemParameters.Tilt.Phi).*sin(theta)+ ...
%   r.^6.*cos (SystemParameters.Tilt.Phi).^2.*cos (SystemParameters.Tilt.Theta).^2.*sin (theta).^2+(-16).* ...
%   M.^2.*sin (PhiMeridian).^2.*sin (theta).^2+(-2).*r.^6.*cos (PhiMeridian).*cos ( ...
%   SystemParameters.Tilt.Phi).*cos (theta).^2.*sin (PhiMeridian).*sin (SystemParameters.Tilt.Phi).*sin(SystemParameters.Tilt.Theta)+( ...
%   -2).*r.^6.*cos (SystemParameters.Tilt.Phi).^2.*cos (theta).*cos (SystemParameters.Tilt.Theta).*sin (PhiMeridian).* ...
%   sin (theta).*sin(SystemParameters.Tilt.Theta)+r.^6.*cos (SystemParameters.Tilt.Phi).^2.*cos (theta).^2.* ...
%   sin (PhiMeridian).^2.*sin (SystemParameters.Tilt.Theta).^2).*(4.*M.^2.*cos (PhiMeridian).^2+(-1).* ...
%   r.^6.*cos (SystemParameters.Tilt.Phi).^2.*cos (theta).^2.*cos (SystemParameters.Tilt.Theta).^2+4.*M.^2.* ...
%   cos (theta).^2.*sin (PhiMeridian).^2+2.*r.^6.*cos (PhiMeridian).*cos (SystemParameters.Tilt.Phi).*cos ( ...
%   theta).*cos (SystemParameters.Tilt.Theta).*sin (SystemParameters.Tilt.Phi).*sin(theta)+(-1).*r.^6.*cos ( ...
%   PhiMeridian).^2.*sin (SystemParameters.Tilt.Phi).^2.*sin (theta).^2+(-2).*r.^6.*cos(SystemParameters.Tilt.Phi) ...
%   .^2.*cos (theta).*cos (SystemParameters.Tilt.Theta).*sin (PhiMeridian).*sin (theta).*sin( ...
%   SystemParameters.Tilt.Theta)+2.*r.^6.*cos (PhiMeridian).*cos (SystemParameters.Tilt.Phi).*sin (PhiMeridian).*sin(SystemParameters.Tilt.Phi) ...
%   .*sin (theta).^2.*sin(SystemParameters.Tilt.Theta)+(-1).*r.^6.*cos (SystemParameters.Tilt.Phi).^2.*sin ( ...
%   PhiMeridian).^2.*sin (theta).^2.*sin (SystemParameters.Tilt.Theta).^2)).^(1/2));





% 
% (4.*(1+beta).^(1/2).*M.*sin(theta)+r.^3.*(2.*B_CAN_r+cos(theta).* ...
%   cos(SystemParameters.Tilt.Theta).*sin(SystemParameters.Tilt.Phi)+(-1).*cos(SystemParameters.Tilt.Phi).*sin(theta))).^( ...
%   -1).*(2.*(1+beta).^(1/2).*M.*r.*cos(theta)+r.^4.*((-2).*B_CAN_theta+ ...
%   cos(SystemParameters.Tilt.Phi).*cos(theta).*cos(SystemParameters.Tilt.Theta)+sin(SystemParameters.Tilt.Phi).*sin(theta)) ...
%   );

end